[package]
name = "omni"
version = "0.1.1"
edition = "2024"
authors = [ "Deekshith vaggu <vaggudeekshith@gmail.com>" ]

[dependencies]
colorize = "0.1.0"
clap = { version = "4.5.57", features = ["derive"] }
